import { catchErrors } from "../utils/catchErrors.js";

export const register = catchErrors(async (req, res, next) => {

})